allow_writeable_chroot=YES
anonymous_enable=NO
chroot_local_user=YES
listen=NO
listen_ipv6=YES
listen_port=$FTP_LISTEN_PORT
local_enable=YES
local_umask=022
ls_recurse_enable=YES
pam_service_name=vsftpd
pasv_max_port=$FTP_PASV_MAX_PORT
pasv_min_port=$FTP_PASV_MIN_PORT
rsa_cert_file=/etc/letsencrypt/live/honifuwa.com/fullchain.pem
rsa_private_key_file=/etc/letsencrypt/live/honifuwa.com/privkey.pem
seccomp_sandbox=NO
ssl_ciphers=HIGH
ssl_enable=YES
write_enable=YES
