ssl_certificate      /etc/letsencrypt/live/honifuwa.com/fullchain.pem;
ssl_certificate_key  /etc/letsencrypt/live/honifuwa.com/privkey.pem;
ssl_stapling         on;
ssl_stapling_verify  on;
resolver             8.8.8.8;
